---
all:
  hosts:
    # Local
    local:
      ansible_host: 127.0.0.1
      ansible_connection: local
  children:
    #AWS
    full:
      hosts:
        node1:
          ansible_host: "{{ lookup('env', 'AWS_NODE1') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        node2:
          ansible_host: "{{ lookup('env', 'AWS_NODE2') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        node3:
          ansible_host: "{{ lookup('env', 'AWS_NODE3') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        node4:
          ansible_host: "{{ lookup('env', 'AWS_NODE4') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        node_db:
          ansible_host: "{{ lookup('env', 'AWS_DB') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        node_sim:
          ansible_host: "{{ lookup('env', 'AWS_SIM') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    pereche_1:
      hosts:
        node1:
        node2:
    pereche_2:
      hosts:
        node3:
        node4:
    pereche_3:
      hosts:
        node_db:
        node_sim:
