all:
  hosts:
    localhost
  children:
    ips:
      hosts:
        ips-node1:
          ansible_host: 10.116.241.235
          ansible_user: root
        ips-node2:
          ansible_host: 10.116.247.133
          ansible_user: root
        ips-node3:
          ansible_host: 10.116.231.180
          ansible_user: root
        ips-node4:
          ansible_host: 10.116.244.124
          ansible_user: root
        ips-database:
          ansible_host: 10.116.254.145
          ansible_user: root
        ips-simulator:
          ansible_host: 10.116.255.180
          ansible_user: root
      children:
        monitoring:
          children:
            logstash:
            elasticsearch:
            kibana:
            filebeat:
            metricbeat:
            apmserver:
            apmagent:
        files-service:
          children:
            service:
              children:
                switch:
                  children:
                    switch_1:
                      hosts:
                        ips-node1:
                    switch_2:
                      hosts:
                        ips-node2:
                    switch_3:
                      hosts:
                        ips-node3:
                    switch_4:
                      hosts:
                        ips-node4:
                lmgr:
                  children:
                    lmgr_1:
                      hosts:
                        ips-node1:
                    lmgr_2:
                      hosts:
                        ips-node2:
                    lmgr_3:
                      hosts:
                        ips-node3:
                    lmgr_4:
                      hosts:
                        ips-node4:
                swrabbitmq:
                  children:
                    swrabbitmq_1:
                      hosts:
                        ips-node1:
                    swrabbitmq_2:
                      hosts:
                        ips-node2:
                    swrabbitmq_3:
                      hosts:
                        ips-node3:
                    swrabbitmq_4:
                      hosts:
                        ips-node4:
                backoffice:
                  children:
                    backoffice_1:
                      hosts:
                        ips-node1:
                    backoffice_2:
                      hosts:
                        ips-node3:
                maps:
                  children:
                    maps_1:
                      hosts:
                        ips-node1:
                    maps_2:
                      hosts:
                        ips-node2:
                    maps_3:
                      hosts:
                        ips_node3:
                    maps_4:
                      hosts:
                        ips-node4:
                mapsrabbitmq:
                  children:
                    mapsrabbitmq_1:
                      hosts:
                        ips-node1:
                    mapsrabbitmq_2:
                      hosts:
                        ips-node2:
                    mapsrabbitmq_3:
                      hosts:
                        ips-node3:
                    mapsrabbitmq_4:
                      hosts:
                        ips-node4:
                transformer:
                  children:
                    transformer_1:
                      hosts:
                        ips-simulator:
                legacy_dsp:
                  children:
                    legacy_dsp_1:
                      hosts:
                        ips-simulator:
                dsp:
                  children:
                    dsp_3:
                        ips-node2:
                    dsp_4:
                      hosts:
                        ips-node4:
                msim:
                  children:
                    msim_1:
                      hosts:
                        ips-simulator:
                swmq:
                  children:
                    swmq_1:
                      hosts:
                        ips-node1:
                    swmq_2:
                      hosts:
                        ips-node3:
                    swmq_combined:
                bankmq:
                  children:
                    bankmq_1:
                      hosts:
                        ips-node1:
                    bankmq_2:
                      hosts:
                        ips-node3:
                    bankmq_combined:
                borabbitmq:
                  children:
                    borabbitmq_1:
                      hosts:
                        ips-database:
                ldap:
                  children:
                    ldap_1:
                      hosts:
                        ips-node1:
                    ldap_2:
                      hosts:
                        ips-node3:
                opsui:
                  children:
                    opsui_1:
                      hosts:
                        ips-simulator:
                msimgui:
                  children:
                    msimgui_1:
                      hosts:
                        ips_simulator:
        files-database:
          children:
            database:
              children:
                analyticaldb:
                  children:
                    analyticaldb_1:
                      hosts:
                          ips-database:
                transactiondb:
                  children:
                    transactiondb_1:
                      hosts:
                        ips-database:
    middleware-db2:
      children:
        database:
    middleware-mq9:
      children:
        swmq:
        msim:
    middleware-java:
      children:
        dsp:
        maps:
    middleware-websphere:
      children:
        opsui:
        backoffice:
        transformer:
        msimgui:
    erlang:
      children:
        switch:
        lmgr:
        rabbitmq:
        msim:
    rabbitmq:
      children:
        single_rabbitmq:
          children:
            borabbitmq:
        cluster_rabbitmq:
          children:
            swrabbitmq:
            mapsrabbitmq: