---
all:
  hosts:
    # Local
    local:
      ansible_host: 127.0.0.1
      ansible_connection: local
  children:
    #AWS
    aws:
      hosts:
        node1:
          ansible_host: "{{ lookup('env', 'AWS_NODE1') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        node2:
          ansible_host: "{{ lookup('env', 'AWS_NODE2') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        node3:
          ansible_host: "{{ lookup('env', 'AWS_NODE3') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        node4:
          ansible_host: "{{ lookup('env', 'AWS_NODE4') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        node_db:
          ansible_host: "{{ lookup('env', 'AWS_DB') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        node_sim:
          ansible_host: "{{ lookup('env', 'AWS_SIM') }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa' }}"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    simulation_of_mq_nodes:
      hosts:
        node1:
        node3:
    simulation_of_rabbitmq_nodes:
      hosts:
        node2:
        node4:
    simulation_of_db_nodes: 
      hosts: 
        node_db:
        node_sim:
    test_new_group:
      hosts:
        node1:
        node3: