---
- name: Conditionals at variables
  hosts: backoffice
  gather_facts: false
  tasks:
    - name: List packages
      shell: 
        cmd: |
          echo AA BB CC \
            A1 B1 C1 \
            A2 B2 C2 \
            "AA-{{ 
              variabila_conditionata | default("Site1")) if 'site_1' in group_names else 
              variabila_conditionata | default("Site2") if 'site_2' in group_names else 
              "Altceva" 
            }}-BB"
      register: result

    - name: Debug
      debug:
        var: result.stdout_lines
