---
- name: Read variables
  hosts: all
  gather_facts: false
  vars:
    base_dir: /local/AnsiblePlay
    file_path: /local/vars/extra-vars.yml
  tasks:
    - name: ReadYMLFile
      include_tasks: tasks/ReadYMLFile.yml

- name: Playing with Ansible
  hosts: backoffice
  gather_facts: false
  tasks:
    - name: Debug RPM var
      debug:
        var: ips_backoffice_rpm

    - name: Ensure directories exist
      file:
        path: "{{ rpm_dir }}"
        state: directory

    - name: Copy RPM to host
      copy:
        src: "{{ rpm_source }}/{{ ips_backoffice_rpm }}"
        dest: "{{ rpm_dir }}/{{ ips_backoffice_rpm }}"

    - name: List packages BEFORE
      shell:
        cmd: |
          rpm -qa | grep 'backoffice'
      register: result

    - name: Debug BEFORE
      debug:
        var: result

    - name: RPM install
      yum:
        name: "{{ rpm_dir }}/{{ ips_backoffice_rpm }}"
        state: present
        disable_gpg_check: yes

    - name: List packages AFTER
      shell:
        cmd: |
          rpm -qa | grep 'backoffice'
      register: result

    - name: Debug AFTER
      debug:
        var: result
