---
- name: Playing with Ansible
  hosts: msim
  gather_facts: false
  tasks:
    - name: Debug
      debug:
        msg: "{{ inventory_hostname }}"

    - name: Debug
      debug:
        msg: "{{ group_names }}"

    # - name: Debug
    #   debug:
    #     msg: "{{ variabila_conditionata }}"